### ISSUE TITLE
ERROR TypeError: Cannot read property 'showFilePicker' of undefined

### ISSUE THREAD

**Issue by Avareto** [epicshaggy/capacitor-file-picker#1]
Hi!
I am not able to get your plugin to work, with IONIC 5.x and Capacitor 2.3.x. I am follwing your sample, but the plugin reference variable is alway undefined:

```
import { Plugins  } from '@capacitor/core';
const { FilePicker } = Plugins;
....
// ERROR TypeError: Cannot read property 'showFilePicker' of undefined.
FilePicker.showFilePicker(...)

```
Any idea what went wrong?
Would be very helpfull if you could provide a minimal running sample within your repository.

Thanks and Regards!
Avareto

**Comment by divyanshverma** [comment]
+1

**Comment by Avareto** [comment]
Now its working fine! 

You have to add the plugin to MainActivit.java android/app/src/main/java/[YourAppBundleId]/MainActivity.java:

```
package [YourAppBundleId];
import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;

import java.util.ArrayList;

**import com.epicshaggy.filepicker.FilePicker;**

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      **add(FilePicker.class);**
    }});
  }
}

```
Your also have to import "FilePickerResult" in your code:

```
...
import { FilePickerResult } from 'capacitor-file-picker';
...
```

**Comment by epicshaggy** [comment]
Glad you got it working, added that step to the readme!  If you need more file type support just leave an issue or feel free to submit a PR.
