### ISSUE TITLE
Support For Capacitor 3 && File types not working

### ISSUE THREAD

**Issue by phoenix503** [epicshaggy/capacitor-file-picker#4]
The import from @capacitor/core is deprecated from Capacitor v3.

Also even after adding file type to only "image/*" i am able to select PDF file also.
It can be viewed in file manager

**Comment by epicshaggy** [comment]
I added support for capacitor 3, give it a go and let me know if you still have problems.

**Comment by phoenix503** [comment]
Yes, it is working fine .
Thanks
